= WFLY-11868 REST integration with WildFly Elytron - AuthenticationClient for Authentication / SSL
:author:            Diana Vilkolakova
:email:             dvilkola@redhat.com
:toc:               left
:icons:             font
:keywords:          elytron, client, resteasy
:idprefix:
:idseparator:       -

== Overview

WildFly Elytron uses the Elytron Client project to enable remote clients to authenticate using Elytron.
Elytron client is already used by other WildFly clients allowing for both use of an Elytron API and pre-defined configurations in the xml file (https://docs.jboss.org/author/display/WFLY/WildFly+Client+Configuration#WildFlyClientConfiguration-wildflyconfig.xmlDiscovery[wildfly-config.xml]).

This requested feature is about making use of Elytron's configuration on the client side of REST deployment so that the RESTEasy client supports the common framework available within the application server.

The implementation will involve loading of configuration from Elytron client, specifically `credentials`, `bearer token` and `SSL context`, and making those available to the RESTEasy client. Credentials will be used for `HTTP Basic authentication` and bearer token for `Bearer Authentication`.

Elytron configuration should be ignored if different configuration was already set. So if there was already Bearer token or credentials available this implementation will not overwrite it.

== Issue Metadata

=== Issue

* https://issues.jboss.org/browse/WFLY-11868[WFLY-11868]

=== Related Issues

* https://issues.jboss.org/browse/EAP7-1219[EAP7-1219]

=== Dev Contacts

* mailto:dvilkola@redhat.com[Diana Vilkolakova]

=== QE Contacts

* mailto:mkopecky@redhat.com[Marek Kopecky]

=== Testing By
// Put an x in the relevant field to indicate if testing will be done by Engineering or QE.
// Discuss with QE during the Kickoff state to decide this
[x] Engineering

[ ] QE

=== Affected Projects or Components

* WildFly Elytron
* RESTEasy

=== Other Interested Projects

N/A

== Requirements

=== Hard Requirements

This RFE seeks to make use of `credentials`, `bearer token` and `SSL context` from the Elytron client in the RESTEasy client. Credentials (if present in form of username and password) will be used for `HTTP Basic authentication`.

RESTEasy client will load Elytron config by default if this configuration is present in wildfly-config.xml (or is provided in the client's code by using Elytron API).

Any existing configuration the client already had configured should not be re-written.

=== Nice-to-Have Requirements

=== Non-Requirements

== Implementation Plan

Because we do not want RESTEasy to have Elytron dependency, new SPI for client configuration will be added to RESTEasy that Elytron will implement. This SPI will be used during configuration of client. Likely in RESTEasyClientBuilder class (in constructor or build method).

To invoke requests, the RESTEasy client uses single instance of ClientHttpEngine interface implementation, which can have only one SSLContext defined. However, Elytron client configuration can have multiple credentials and SSL contexts specified and these are chosen based on rules, eg. URI. It might be necessary to intercept/filter the requests and choose credentials, bearer token or SSLContext based on the destination of the requests.

#### Multiple credentials set in RESTEasy client

To use HTTP Basic credentials or HTTP Bearer token, either RequestClientFilter will be registered or BasicCredentialsProvider will be set. WebTarget has its own Configuration instance that allows to set specific configuration options per target resource. This might be good to specify credentials or bearer token.

#### Multiple SSLContexts set in RESTEasy client

Specifying multiple SSL contexts for single RESTEasy client might be a bit more tricky.
ClientHttpEngineBuilder sets SSLConnectionSocketFactory during build. This factory prepares and creates sockets with specific SSLContext.
During creation of socket, SSLConnectionSocketFactory can make use of HttpContext received from the engine (HttpContext has various useful attributes defined).

To be able to configure multiple SSLContexts for RESTEasy client, there are 2 solutions I could think of, but this will become more clear during actual implementation:

* Have multiple ClientHttpEngines defined for one client.
* Add a new implementation of SSLConnectionSocketFactory which will behave as a wrapper that will resolve which SSLContext to use and then delegate the creation of socket to appropriate SSLConnectionSocketFactory instance.
The wrapper could decide which SSLContext to use based on HTTPContext's attributes it receives from the apache engine in createSocket and connectSocket methods (org.apache.http.conn.socket.ConnectionSocketFactory).

== Test Plan

Functionality tests in RESTEasy testsuite.
